# general
gpu_id: 0
use_gpu: True
seed: [2024]
data_path: '../dataset/'
num_workers: 0
batch_size: 256
save_model: False

# training settings
epochs: 100
stopping_step: 5
learner: adamW
learning_rate: 1e-4
learning_rate_scheduler: [1.0, 50]
weight_decay: 5e-5
eval_step: 1

# evaluation settings
metrics: ["Acc", "F1", "Precision", "Recall"]
valid_metric: Acc

# iteration parameters
hyper_parameters: ["seed","batch_size"]

# feature dim
audio_dim: 1024
image_dim: 1024
text_dim: 1024
